[new] try jenkins integration with debian11 test

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -90,6 +90,25 @@ getversion opsi-quick-install:
     - cd build/
     - rm -rf opsi-quickinstall/l-opsi-server
 
+.jenkinsintegrationtest: &jenkinsintegrationtest |
+  response=$(curl --insecure -v -X POST https://jenkinsttt.uib.local/job/4.2/debian11-qi.experimental42 2>&1)
+  url=$(echo "$response" | grep "Location" | grep -o 'https://.*/')   # this is the global queue id
+  echo "waiting for start of queue item $url"
+  sleep 20
+  response=$(curl --insecure "$url/api/json" 2> /dev/null)
+  echo "$response"
+  while echo "$response" | grep -q '"blocked":true'; do echo "waiting for job start"; sleep 20; response=$(curl --insecure "$url/api/json" 2> /dev/null); done
+  url=$(echo "$response" | grep -o 'https://[^"]*[0-9]\+/')           # this is the specific build id for the pipeline
+  echo "waiting for completion of job $url"
+  response=$(curl --insecure "$url/api/json" 2> /dev/null)
+  while echo "$response" | grep -q '"result":null'; do echo "still waiting"; sleep 20; response=$(curl --insecure "$url/api/json" 2> /dev/null); done
+  echo "$response"
+  if echo "$response" | grep -q '"result":"SUCCESS"'; then echo 'result:SUCCESS'; exit 0; fi
+  echo 'NOT successful'
+  response=$(curl --insecure "$url/consoleText/api/json" 2> /dev/null)
+  echo "$response" | grep "Failed in branch"
+  exit 1
+
 upload opsi-quick-install:
   stage: upload
   rules:
@@ -98,6 +117,7 @@ upload opsi-quick-install:
     - '[ "$CI_COMMIT_TAG" == "" ] && ./opsi-dev-tool --log-level info --uib-binaryindex-password=ahx9taePhu --binary-push opsi-quickinstall opsi-quick-install linux x64 $MAINVERSION-$SUBVERSION "$CI_JOB_ID"'
     - '[ "$CI_COMMIT_BRANCH" == "main" && "$CI_COMMIT_TAG" != "" ] && ./opsi-dev-tool --uib-binaryindex-password=ahx9taePhu --binary-cleanup opsi-quick-install linux x64'
     - '[ "$CI_COMMIT_BRANCH" == "main" && "$CI_COMMIT_TAG" != "" ] && ./opsi-dev-tool --log-level info --uib-binaryindex-password=ahx9taePhu --binary-push opsi-quickinstall opsi-quick-install linux x64 $MAINVERSION-$SUBVERSION'
+    - *jenkinsintegrationtest
 
 publish opsi-quick-install:
   stage: publish
